routes/web.php
<?php

//facebook login
Route::get('login/facebook', 'Auth\LoginController@redirectToProvider')->name('login.facebook');
Route::get('login/facebook/callback', 'Auth\LoginController@handleProviderCallback');

Route::group(['middleware' => 'guest'], function () {
    Route::get('register', 'FrontendController@register'); //don't know what is this
    Route::post('register', 'FrontendController@StoreRegister');// don't know what is this

    Route::get('createHere', 'FrontendController@createHere'); // step one for all types

    Route::get('registerfront', 'FrontendController@registerfront'); //for public user register by facebook

    Route::get('trade-register', 'FrontendController@trade_register');          //step 1 for trade visitor register
    Route::get('groupleader-register', 'FrontendController@groupleader_register'); //step 1 for groupleader register
    Route::get('register-exhibitor', 'FrontendController@register_exhibitor');  //step 1 for exhibitor register
    Route::get('register-tourguide', 'FrontendController@register_tourguide');  //step 1 for tourguide register

    Route::post('company-info', 'FrontendController@register2')->name('register2'); // step 2 for all types
    Route::post('individual-profile', 'FrontendController@register3')->name('register3');// step 3 for all types
    Route::post('users_login', 'FrontendController@individual_profile')->name('store.user'); // store step

});

Auth::routes(['register' => false]);


Route::get('/', 'FrontendController@index');
Route::get('exhibitor', 'FrontendController@exhibitor');
Route::get('visitor', 'FrontendController@visitor');
Route::get('library', 'FrontendController@library');
Route::get('privacy', 'FrontendController@privacy');
Route::get('tourguide', 'FrontendController@tourguide');

Route::get('termsandcondition', 'FrontendController@termsandcondition');

//Route::post('company-info', 'FrontendController@company_info');

Route::get('tripfam', 'FrontendController@tripfams');
Route::post('tripfam', 'FrontendController@tripfam');


Route::get('news/{id}', 'FrontendController@news');
Route::get('outer-news', 'FrontendController@outer_news');
Route::get('about', 'FrontendController@About');
Route::get('contact', 'FrontendController@contact');
Route::post('mail', 'FrontendController@contacts')->name('mail');
Route::get('sponsored', 'FrontendController@sponsored');
Route::get('destinationpartner', 'FrontendController@destinationpartner');


Route::redirect('/home', 'admin');


Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth']], function () {

    Route::get('/', 'DashboardController@index')->name('home');

    Route::delete('permissions/destroy', 'PermissionsController@massDestroy')->name('permissions.massDestroy');

    Route::resource('permissions', 'PermissionsController');

    Route::delete('roles/destroy', 'RolesController@massDestroy')->name('roles.massDestroy');

    Route::resource('roles', 'RolesController');

    Route::delete('users/destroy', 'UsersController@massDestroy')->name('users.massDestroy');

    Route::resource('users', 'UsersController');

    Route::delete('products/destroy', 'ProductsController@massDestroy')->name('products.massDestroy');

    Route::resource('products', 'ProductsController');

    Route::delete('visitors/destroy', 'VisitorsController@massDestroy')->name('visitors.massDestroy');
    Route::resource('visitors', 'VisitorsController');

    Route::delete('exhibitors/destroy', 'ExhibitorsController@massDestroy')->name('exhibitors.massDestroy');
    Route::resource('exhibitors', 'ExhibitorsController')->only('index', 'show', 'destroy');

    Route::delete('tourguides/destroy', 'TourGuidesController@massDestroy')->name('tourguides.massDestroy');
    Route::resource('tourguides', 'TourGuidesController')->only('index', 'show', 'destroy');


    Route::delete('searchs/destroy', 'SearchController@massDestroy')->name('searchs.massDestroy');

    Route::resource('searchs', 'SearchController');

    Route::delete('rates/destroy', 'RatesController@massDestroy')->name('rates.massDestroy');

    Route::resource('rates', 'RatesController');

    Route::delete('forms/destroy', 'FormsController@massDestroy')->name('forms.massDestroy');

    Route::resource('forms', 'FormsController');

    Route::delete('offers/destroy', 'OffersController@massDestroy')->name('offers.massDestroy');
    Route::resource('offers', 'OffersController');


    Route::post('results', 'ResultsController@result')->name('results');
    Route::get('results/show/profile/{id}', 'ResultsController@showProfile')->name('results.show.profile');

    Route::delete('abouts/destroy', 'AboutController@massDestroy')->name('abouts.massDestroy');

    Route::resource('abouts', 'AboutController');

    Route::delete('slides/destroy', 'SlideController@massDestroy')->name('slides.massDestroy');

    Route::resource('slides', 'SlideController');

    Route::delete('leaders/destroy', 'LeaderController@massDestroy')->name('leaders.massDestroy');
    Route::resource('leaders', 'LeaderController')->only('index', 'show', 'destroy');

    Route::delete('librarys/destroy', 'LibraryController@massDestroy')->name('librarys.massDestroy');

    Route::resource('librarys', 'LibraryController');

    Route::delete('contactus/destroy', 'ContactUsController@massDestroy')->name('contactus.massDestroy');

    Route::resource('contactus', 'ContactUsController');

    Route::delete('media/destroy', 'MediaController@massDestroy')->name('media.massDestroy');

    Route::resource('media', 'MediaController');

    Route::delete('dashboard/destroy', 'DashboardController@massDestroy')->name('dashboard.massDestroy');

    Route::resource('dashboard', 'DashboardController');

    Route::delete('articles/destroy', 'ArticleController@massDestroy')->name('articles.massDestroy');

    Route::resource('articles', 'ArticleController');

    Route::delete('fans/destroy', 'FamController@massDestroy')->name('fans.massDestroy');

    Route::resource('fans', 'FamController');

    Route::delete('metas/destroy', 'MetaController@massDestroy')->name('metas.massDestroy');
    Route::resource('metas', 'MetaController');

    Route::resource('sliders', 'SlidersController')->only(['index', 'edit', 'update']);

    Route::delete('myoffers/destroy', 'MyOffersController@massDestroy')->name('myoffers.massDestroy');
    Route::resource('myoffers', 'MyOffersController');


    Route::delete('favourites', 'FavouritesController@massDestroy')->name('favourites.massDestroy');
    Route::get('favourites', 'FavouritesController@index')->name('favourites.index');
    Route::get('favourites/{id}', 'FavouritesController@show')->name('favourites.show');
    Route::post('favourites', 'FavouritesController@addFavourite')->name('favourites.add');
    Route::delete('favourites/destroy/{id}', 'FavouritesController@deleteFavourite')->name('favourites.delete');

    Route::get('edit/profile', 'ProfileController@edit')->name('edit.profile');
    Route::patch('edit/profile', 'ProfileController@update')->name('update.profile');
    Route::get('show/profile', 'ProfileController@show')->name('show.profile');
    Route::post('download/{id}', 'ProfileController@Download')->name('companyProfile.download');


});

app/Visitor.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Visitor extends Model
{
    //
}

app/Http/Controllers/Admin/VisitorsController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use Illuminate\Http\Request\UpdateVisitorRequest;
use Illuminate\Http\Request\MassDestroyVisitorRequest;
use App\Http\Controllers\Controller;
use App\User;
use Illuminate\Support\Facades\Storage;

class VisitorsController extends Controller
{


    public function index()
    {
        abort_unless(\Gate::allows('visitor_access'), 403);

        $users = User::all()->where('status', 1);

        return view('admin.visitors.index', compact('users'));
    }

//    public function create()
//    {
//        abort_unless(\Gate::allows('visitor_create'), 403);
//
//        $roles = Role::all()->pluck('title', 'id');
//
//        return view('admin.users.create', compact('roles'));
//    }
//
//    public function store(StoreUserRequest $request)
//    {
//        abort_unless(\Gate::allows('user_create'), 403);
//
//        $user = User::create($request->all());
//        $user->roles()->sync($request->input('roles', []));
//
//        return redirect()->route('admin.users.index');
//    }
//
//    public function edit(User $user)
//    {
//        abort_unless(\Gate::allows('user_edit'), 403);
//
//        $roles = Role::all()->pluck('title', 'id');
//
//        $user->load('roles');
//
//        return view('admin.users.edit', compact('roles', 'user'));
//    }
//
//    public function update(UpdateUserRequest $request, User $user)
//    {
//        abort_unless(\Gate::allows('user_edit'), 403);
//
//        $user->update($request->all());
//        $user->roles()->sync($request->input('roles', []));
//
//        return redirect()->route('admin.users.index');
//    }

    public function show($id)
    {
        abort_unless(\Gate::allows('visitor_show'), 403);

        $user = User::findOrFail($id);
        if ($user->status == 1) {
            return view('admin.visitors.show', compact('user'));
        }

        return redirect()->back();

    }

    public function destroy($id)
    {
        abort_unless(\Gate::allows('user_delete'), 403);
        $user = User::findorFail($id);
        if ($user->status == 1) {

           if($user->imgCompany != '/noimage.png'){
                $path = str_replace('/storage/', 'public/', $user->imgCompany);
                Storage::delete($path);
            }
            if($user->imgPersonal != '/noimage.png'){
                $path = str_replace('/storage/', 'public/', $user->imgPersonal);
                Storage::delete($path);
            }
            $user->delete();
        }
        return back();
    }

    public function massDestroy()
    {
        $users = User::whereIn('id', request('ids'))->get();

        foreach ($users as $user) {
            if($user->imgCompany != '/noimage.png'){
                $path = str_replace('/storage/', 'public/', $user->imgCompany);
                Storage::delete($path);
            }
            if($user->imgPersonal != '/noimage.png'){
                $path = str_replace('/storage/', 'public/', $user->imgPersonal);
                Storage::delete($path);
            }
            $user->delete();
        }
        return response(null, 204);
    }


}

resources/views/admin/visitors/create.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.create') }} {{ trans('global.user.title_singular') }}
    </div>

    <div class="card-body">
        <form action="{{ route("admin.users.store") }}" method="POST" enctype="multipart/form-data">
            @csrf
            <div class="form-group {{ $errors->has('name') ? 'has-error' : '' }}">
                <label for="name">{{ trans('global.user.fields.name') }}*</label>
                <input type="text" id="name" name="name" class="form-control" value="{{ old('name', isset($user) ? $user->name : '') }}">
                @if($errors->has('name'))
                    <em class="invalid-feedback">
                        {{ $errors->first('name') }}
                    </em>
                @endif
                <p class="helper-block">
                    {{ trans('global.user.fields.name_helper') }}
                </p>
            </div>
            <div class="form-group {{ $errors->has('email') ? 'has-error' : '' }}">
                <label for="email">{{ trans('global.user.fields.email') }}*</label>
                <input type="email" id="email" name="email" class="form-control" value="{{ old('email', isset($user) ? $user->email : '') }}">
                @if($errors->has('email'))
                    <em class="invalid-feedback">
                        {{ $errors->first('email') }}
                    </em>
                @endif
                <p class="helper-block">
                    {{ trans('global.user.fields.email_helper') }}
                </p>
            </div>
            <div class="form-group {{ $errors->has('password') ? 'has-error' : '' }}">
                <label for="password">{{ trans('global.user.fields.password') }}</label>
                <input type="password" id="password" name="password" class="form-control">
                @if($errors->has('password'))
                    <em class="invalid-feedback">
                        {{ $errors->first('password') }}
                    </em>
                @endif
                <p class="helper-block">
                    {{ trans('global.user.fields.password_helper') }}
                </p>
            </div>
            <div class="form-group {{ $errors->has('roles') ? 'has-error' : '' }}">
                <label for="roles">{{ trans('global.user.fields.roles') }}*
                    <span class="btn btn-info btn-xs select-all">Select all</span>
                    <span class="btn btn-info btn-xs deselect-all">Deselect all</span></label>
                <select name="roles[]" id="roles" class="form-control select2" multiple="multiple">
                    @foreach($roles as $id => $roles)
                        <option value="{{ $id }}" {{ (in_array($id, old('roles', [])) || isset($user) && $user->roles->contains($id)) ? 'selected' : '' }}>
                            {{ $roles }}
                        </option>
                    @endforeach
                </select>
                @if($errors->has('roles'))
                    <em class="invalid-feedback">
                        {{ $errors->first('roles') }}
                    </em>
                @endif
                <p class="helper-block">
                    {{ trans('global.user.fields.roles_helper') }}
                </p>
            </div>
            <div>
                <input class="btn btn-danger" type="submit" value="{{ trans('global.save') }}">
            </div>
        </form>
    </div>
</div>

@endsection

resources/views/admin/visitors/edit.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.edit') }} {{ trans('global.user.title_singular') }}
    </div>

    <div class="card-body">
        <form action="{{ route("admin.users.update", [$user->id]) }}" method="POST" enctype="multipart/form-data">
            @csrf
            @method('PUT')
            <div class="form-group {{ $errors->has('name') ? 'has-error' : '' }}">
                <label for="name">{{ trans('global.user.fields.name') }}*</label>
                <input type="text" id="name" name="name" class="form-control" value="{{ old('name', isset($user) ? $user->name : '') }}">
                @if($errors->has('name'))
                    <em class="invalid-feedback">
                        {{ $errors->first('name') }}
                    </em>
                @endif
                <p class="helper-block">
                    {{ trans('global.user.fields.name_helper') }}
                </p>
            </div>
            <div class="form-group {{ $errors->has('email') ? 'has-error' : '' }}">
                <label for="email">{{ trans('global.user.fields.email') }}*</label>
                <input type="email" id="email" name="email" class="form-control" value="{{ old('email', isset($user) ? $user->email : '') }}">
                @if($errors->has('email'))
                    <em class="invalid-feedback">
                        {{ $errors->first('email') }}
                    </em>
                @endif
                <p class="helper-block">
                    {{ trans('global.user.fields.email_helper') }}
                </p>
            </div>
            <div class="form-group {{ $errors->has('password') ? 'has-error' : '' }}">
                <label for="password">{{ trans('global.user.fields.password') }}</label>
                <input type="password" id="password" name="password" class="form-control">
                @if($errors->has('password'))
                    <em class="invalid-feedback">
                        {{ $errors->first('password') }}
                    </em>
                @endif
                <p class="helper-block">
                    {{ trans('global.user.fields.password_helper') }}
                </p>
            </div>
            <div class="form-group {{ $errors->has('roles') ? 'has-error' : '' }}">
                <label for="roles">{{ trans('global.user.fields.roles') }}*
                    <span class="btn btn-info btn-xs select-all">Select all</span>
                    <span class="btn btn-info btn-xs deselect-all">Deselect all</span></label>
                <select name="roles[]" id="roles" class="form-control select2" multiple="multiple">
                    @foreach($roles as $id => $roles)
                        <option value="{{ $id }}" {{ (in_array($id, old('roles', [])) || isset($user) && $user->roles->contains($id)) ? 'selected' : '' }}>
                            {{ $roles }}
                        </option>
                    @endforeach
                </select>
                @if($errors->has('roles'))
                    <em class="invalid-feedback">
                        {{ $errors->first('roles') }}
                    </em>
                @endif
                <p class="helper-block">
                    {{ trans('global.user.fields.roles_helper') }}
                </p>
            </div>
            <div>
                <input class="btn btn-danger" type="submit" value="{{ trans('global.save') }}">
            </div>
        </form>
    </div>
</div>

@endsection

resources/views/admin/visitors/index.blade.php
@extends('layouts.admin')
@section('content')
@can('user_create')
    <!--<div style="margin-bottom: 10px;" class="row">-->
    <!--    <div class="col-lg-12">-->
    <!--        <a class="btn btn-success" href="{{ route("admin.users.create") }}">-->
    <!--            {{ trans('global.add') }} {{ trans('global.user.title_singular') }}-->
    <!--        </a>-->
    <!--    </div>-->
    <!--</div>-->
@endcan
<div class="card">
    <div class="card-header">
        {{ trans('global.visitor.title_singular') }} {{ trans('global.list') }}
    </div>

    <div class="card-body">
        <div class="table-responsive">
            <table class=" table table-bordered table-striped table-hover datatable">
                <thead>
                    <tr>
                        <th width="10">

                        </th>


                        <th>
                            {{ trans('global.visitor.fields.company') }}
                        </th>

                        <th>
                            {{ trans('global.user.fields.name') }}
                        </th>
                        <th>
                            {{ trans('global.user.fields.email') }}
                        </th>
                        <!--<th>-->
                        <!--    {{ trans('global.user.fields.email_verified_at') }}-->
                        <!--</th>-->
                        <!--<th>-->
                        <!--    {{ trans('global.user.fields.roles') }}-->
                        <!--</th>-->
                        <th>
                            &nbsp;
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($users as $key => $user)
                        <tr data-entry-id="{{ $user->id }}">
                            <td>

                            </td>
                            <td>
                                {{ $user->company ?? '' }}
                            </td>
                            <td>
                                {{ $user->name ?? '' }}
                            </td>

                            <td>
                                {{ $user->email ?? '' }}
                            </td>
                            <!--<td>-->
                            <!--    {{ $user->email_verified_at ?? '' }}-->
                            <!--</td>-->
                            <!--<td>-->
                            <!--    @foreach($user->roles as $key => $item)-->
                            <!--        <span class="badge badge-info">{{ $item->title }}</span>-->
                            <!--    @endforeach-->
                            <!--</td>-->
                            <td>
                                @can('visitor_show')
                                    <a class="btn btn-xs btn-primary" href="{{ route('admin.visitors.show', $user->id) }}">
                                        {{ trans('global.view') }}
                                    </a>
                                @endcan
                                @can('user_delete')
                                    <form action="{{ route('admin.visitors.destroy', $user->id) }}" method="POST" onsubmit="return confirm('{{ trans('global.areYouSure') }}');" style="display: inline-block;">
                                        <input type="hidden" name="_method" value="DELETE">
                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                        <input type="submit" class="btn btn-xs btn-danger" value="{{ trans('global.delete') }}">
                                    </form>
                                @endcan
                            </td>

                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>
@section('scripts')
@parent
<script>
    $(function () {
  let deleteButtonTrans = '{{ trans('global.datatables.delete') }}'
  let deleteButton = {
    text: deleteButtonTrans,
    url: "{{ route('admin.visitors.massDestroy') }}",
    className: 'btn-danger',
    action: function (e, dt, node, config) {
      var ids = $.map(dt.rows({ selected: true }).nodes(), function (entry) {
          return $(entry).data('entry-id')
      });

      if (ids.length === 0) {
        alert('{{ trans('global.datatables.zero_selected') }}')

        return
      }

      if (confirm('{{ trans('global.areYouSure') }}')) {
        $.ajax({
          headers: {'x-csrf-token': _token},
          method: 'POST',
          url: config.url,
          data: { ids: ids, _method: 'DELETE' }})
          .done(function () { location.reload() })
      }
    }
  }
  let dtButtons = $.extend(true, [], $.fn.dataTable.defaults.buttons)
@can('user_delete')
  dtButtons.push(deleteButton)
@endcan

  $('.datatable:not(.ajaxTable)').DataTable({ buttons: dtButtons })
})

</script>
@endsection
@endsection

resources/views/admin/visitors/show.blade.php
@extends('layouts.admin')
@section('content')

    <div class="card">
        <div class="card-header">
            {{ trans('global.show') }} {{ trans('global.visitor.title_singular') }}
        </div>

        <div class="card-body">
            <table class="table table-bordered table-striped">
                <tbody>
                <tr>
                    <th>
                        {{ trans('global.user.fields.type') }}
                    </th>
                    <td>
                        {{ $user->type }}
                    </td>
                </tr>
                <tr>
                    <th>
                        {{ trans('global.user.fields.name') }}
                    </th>
                    <td>
                        {{ $user->name }}
                    </td>
                </tr>
                <tr>
                    <th>
                        {{ trans('global.user.fields.last-name') }}
                    </th>
                    <td>
                        {{ $user->last_name }}
                    </td>
                </tr>
                <tr>
                    <th>
                        {{ trans('global.user.fields.email') }}
                    </th>
                    <td>
                        {{ $user->email }}
                    </td>
                </tr>
                <tr>
                    <th>
                        {{ trans('global.user.fields.phone') }}
                    </th>
                    <td>
                        {{ $user->phone }}
                    </td>
                </tr>
                <tr>
                    <th>
                        {{ trans('global.user.fields.imgPersonal') }}
                    </th>
                    <td>
                        <img src="{{ asset($user->imgPersonal) }}" style="height: 50px; width: 100px">
                    </td>
                </tr>
                <tr>
                    <th>
                        {{ trans('global.user.fields.company') }}
                    </th>
                    <td>
                        {{ $user->company }}
                    </td>
                </tr>
                <tr>
                    <th>
                        {{ trans('global.user.fields.company-email') }}
                    </th>
                    <td>
                        {{ $user->company_email }}
                    </td>
                </tr>
                <tr>
                    <th>
                        {{ trans('global.user.fields.imgCompany') }}
                    </th>
                    <td>
                        <img src="{{ asset($user->imgCompany) }}" style="height: 50px; width: 100px">
                    </td>
                </tr>
                <tr>
                    <th>
                        {{ trans('global.user.fields.website') }}
                    </th>
                    <td>
                        <a href="{{ $user->website }}" target="_blank">{{$user->website}}</a>
                    </td>
                </tr>
                @if($user->facebook != null)
                    <tr>
                        <th>
                            {{ trans('global.user.fields.facebook') }}
                        </th>
                        <td>
                            <a href="{{ $user->facebook }}" target="_blank">Facebook</a>
                        </td>
                    </tr>
                @endif
                @if($user->linkedin != null)
                    <tr>
                        <th>
                            {{ trans('global.user.fields.linkedin') }}
                        </th>
                        <td>
                            <a href="{{ $user->linkedin }}" target="_blank">LinkedIn</a>
                        </td>
                    </tr>
                @endif
                @if($user->twitter != null)
                    <tr>
                        <th>
                            {{ trans('global.user.fields.twitter') }}
                        </th>
                        <td>
                            <a href="{{ $user->twitter }}" target="_blank">Twitter</a>
                        </td>
                    </tr>
                @endif
                @if($user->instgram != null)
                    <tr>
                        <th>
                            {{ trans('global.user.fields.instgram') }}
                        </th>
                        <td>
                            <a href="{{ $user->instgram }}" target="_blank">Instagram</a>
                        </td>
                    </tr>
                @endif
                <tr>
                    <th>
                        {{ trans('global.user.fields.designation') }}
                    </th>
                    <td>
                        {{ $user->designation }}
                    </td>
                </tr>
                <tr>
                    <th>
                        {{ trans('global.user.fields.zip-code') }}
                    </th>
                    <td>
                        {{ $user->zip_code }}
                    </td>
                </tr>
                <tr>
                    <th>
                        {{ trans('global.user.fields.country') }}
                    </th>
                    <td>
                        {{ $user->country }}
                    </td>
                </tr>
                <tr>
                    <th>
                        {{ trans('global.user.fields.travel') }}
                    </th>
                    <td>
                        <ul>
                            @foreach($user->travel as $travel)
                                <li>{{$travel}}</li>
                            @endforeach
                        </ul>
                    </td>
                </tr>
                <tr>
                    <th>
                        {{ trans('global.user.fields.languages') }}
                    </th>
                    <td>
                        <ul>
                            @foreach($user->languages as $language)
                                <li>{{$language}}</li>
                            @endforeach
                        </ul>
                    </td>
                </tr>
                <tr>
                    <th>
                        {{ trans('global.user.fields.destination') }}
                    </th>
                    <td>
                        <ul>
                            @foreach($user->destination as $destination)
                                <li>{{$destination}}</li>
                            @endforeach
                        </ul>
                    </td>
                </tr>

                </tbody>
            </table>
        </div>
    </div>

@endsection