routes/web.php
<?php

//facebook login
Route::get('login/facebook', 'Auth\LoginController@redirectToProvider')->name('login.facebook');
Route::get('login/facebook/callback', 'Auth\LoginController@handleProviderCallback');

Route::group(['middleware' => 'guest'], function () {
    Route::get('register', 'FrontendController@register'); //don't know what is this
    Route::post('register', 'FrontendController@StoreRegister');// don't know what is this

    Route::get('createHere', 'FrontendController@createHere'); // step one for all types

    Route::get('registerfront', 'FrontendController@registerfront'); //for public user register by facebook

    Route::get('trade-register', 'FrontendController@trade_register');          //step 1 for trade visitor register
    Route::get('groupleader-register', 'FrontendController@groupleader_register'); //step 1 for groupleader register
    Route::get('register-exhibitor', 'FrontendController@register_exhibitor');  //step 1 for exhibitor register
    Route::get('register-tourguide', 'FrontendController@register_tourguide');  //step 1 for tourguide register

    Route::post('company-info', 'FrontendController@register2')->name('register2'); // step 2 for all types
    Route::post('individual-profile', 'FrontendController@register3')->name('register3');// step 3 for all types
    Route::post('users_login', 'FrontendController@individual_profile')->name('store.user'); // store step

});

Auth::routes(['register' => false]);


Route::get('/', 'FrontendController@index');
Route::get('exhibitor', 'FrontendController@exhibitor');
Route::get('visitor', 'FrontendController@visitor');
Route::get('library', 'FrontendController@library');
Route::get('privacy', 'FrontendController@privacy');
Route::get('tourguide', 'FrontendController@tourguide');

Route::get('termsandcondition', 'FrontendController@termsandcondition');

//Route::post('company-info', 'FrontendController@company_info');

Route::get('tripfam', 'FrontendController@tripfams');
Route::post('tripfam', 'FrontendController@tripfam');


Route::get('news/{id}', 'FrontendController@news');
Route::get('outer-news', 'FrontendController@outer_news');
Route::get('about', 'FrontendController@About');
Route::get('contact', 'FrontendController@contact');
Route::post('mail', 'FrontendController@contacts')->name('mail');
Route::get('sponsored', 'FrontendController@sponsored');
Route::get('destinationpartner', 'FrontendController@destinationpartner');


Route::redirect('/home', 'admin');


Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth']], function () {

    Route::get('/', 'DashboardController@index')->name('home');

    Route::delete('permissions/destroy', 'PermissionsController@massDestroy')->name('permissions.massDestroy');

    Route::resource('permissions', 'PermissionsController');

    Route::delete('roles/destroy', 'RolesController@massDestroy')->name('roles.massDestroy');

    Route::resource('roles', 'RolesController');

    Route::delete('users/destroy', 'UsersController@massDestroy')->name('users.massDestroy');

    Route::resource('users', 'UsersController');

    Route::delete('products/destroy', 'ProductsController@massDestroy')->name('products.massDestroy');

    Route::resource('products', 'ProductsController');

    Route::delete('visitors/destroy', 'VisitorsController@massDestroy')->name('visitors.massDestroy');
    Route::resource('visitors', 'VisitorsController');

    Route::delete('exhibitors/destroy', 'ExhibitorsController@massDestroy')->name('exhibitors.massDestroy');
    Route::resource('exhibitors', 'ExhibitorsController')->only('index', 'show', 'destroy');

    Route::delete('tourguides/destroy', 'TourGuidesController@massDestroy')->name('tourguides.massDestroy');
    Route::resource('tourguides', 'TourGuidesController')->only('index', 'show', 'destroy');


    Route::delete('searchs/destroy', 'SearchController@massDestroy')->name('searchs.massDestroy');

    Route::resource('searchs', 'SearchController');

    Route::delete('rates/destroy', 'RatesController@massDestroy')->name('rates.massDestroy');

    Route::resource('rates', 'RatesController');

    Route::delete('forms/destroy', 'FormsController@massDestroy')->name('forms.massDestroy');

    Route::resource('forms', 'FormsController');

    Route::delete('offers/destroy', 'OffersController@massDestroy')->name('offers.massDestroy');
    Route::resource('offers', 'OffersController');


    Route::post('results', 'ResultsController@result')->name('results');
    Route::get('results/show/profile/{id}', 'ResultsController@showProfile')->name('results.show.profile');

    Route::delete('abouts/destroy', 'AboutController@massDestroy')->name('abouts.massDestroy');

    Route::resource('abouts', 'AboutController');

    Route::delete('slides/destroy', 'SlideController@massDestroy')->name('slides.massDestroy');

    Route::resource('slides', 'SlideController');

    Route::delete('leaders/destroy', 'LeaderController@massDestroy')->name('leaders.massDestroy');
    Route::resource('leaders', 'LeaderController')->only('index', 'show', 'destroy');

    Route::delete('librarys/destroy', 'LibraryController@massDestroy')->name('librarys.massDestroy');

    Route::resource('librarys', 'LibraryController');

    Route::delete('contactus/destroy', 'ContactUsController@massDestroy')->name('contactus.massDestroy');

    Route::resource('contactus', 'ContactUsController');

    Route::delete('media/destroy', 'MediaController@massDestroy')->name('media.massDestroy');

    Route::resource('media', 'MediaController');

    Route::delete('dashboard/destroy', 'DashboardController@massDestroy')->name('dashboard.massDestroy');

    Route::resource('dashboard', 'DashboardController');

    Route::delete('articles/destroy', 'ArticleController@massDestroy')->name('articles.massDestroy');

    Route::resource('articles', 'ArticleController');

    Route::delete('fans/destroy', 'FamController@massDestroy')->name('fans.massDestroy');

    Route::resource('fans', 'FamController');

    Route::delete('metas/destroy', 'MetaController@massDestroy')->name('metas.massDestroy');
    Route::resource('metas', 'MetaController');

    Route::resource('sliders', 'SlidersController')->only(['index', 'edit', 'update']);

    Route::delete('myoffers/destroy', 'MyOffersController@massDestroy')->name('myoffers.massDestroy');
    Route::resource('myoffers', 'MyOffersController');


    Route::delete('favourites', 'FavouritesController@massDestroy')->name('favourites.massDestroy');
    Route::get('favourites', 'FavouritesController@index')->name('favourites.index');
    Route::get('favourites/{id}', 'FavouritesController@show')->name('favourites.show');
    Route::post('favourites', 'FavouritesController@addFavourite')->name('favourites.add');
    Route::delete('favourites/destroy/{id}', 'FavouritesController@deleteFavourite')->name('favourites.delete');

    Route::get('edit/profile', 'ProfileController@edit')->name('edit.profile');
    Route::patch('edit/profile', 'ProfileController@update')->name('update.profile');
    Route::get('show/profile', 'ProfileController@show')->name('show.profile');
    Route::post('download/{id}', 'ProfileController@Download')->name('companyProfile.download');


});

app/Library.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Library extends Model
{
    protected $table="librarys";
    
     use SoftDeletes;

    protected $dates = [
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    protected $fillable = [
        'name',
        'video',
        'created_at',
        'updated_at',
        'deleted_at',
    ];
}

app/Http/Controllers/Admin/LibraryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\MassDestroyLibraryRequest;
use App\Http\Requests\StoreLibraryRequest;
use App\Http\Requests\UpdateLibraryRequest;
use App\Library;

class LibraryController extends Controller
{
    public function index()
    {
        abort_unless(\Gate::allows('library_access'), 403);

        $librarys = Library::all();

        return view('admin.librarys.index',compact('librarys'));
    }

    public function create()
    {
        abort_unless(\Gate::allows('library_create'), 403);
        
        return view('admin.librarys.create');
    }

    public function store(StoreLibraryRequest $request)
    {
        abort_unless(\Gate::allows('library_create'), 403);

        $video = $request->file('video');
        $video_new_name = '/uploads/librarys/' . time().$video->getClientOriginalName();
        $video->move('uploads/librarys',$video_new_name);
        
        $library = Library::create([
               'name'=>$request->name,
               'video'=>$video_new_name,
            
            ]);

        return redirect()->route('admin.librarys.index');
    }

    public function edit(Library $library)
    {
        abort_unless(\Gate::allows('library_edit'), 403);

        return view('admin.librarys.edit', compact('library'));
    }

    public function update(UpdateLibraryRequest $request, Library $library)
    {
        abort_unless(\Gate::allows('library_edit'), 403);
        $input = $request->except('video');
       if($request->hasFile('video') && !empty($request->video)){
        //delete video
        unlink(public_path() . $library->video);
        //add new video
        $video = $request->file('video');
        $video_new_name = '/uploads/librarys/' . time().$video->getClientOriginalName();
        $video->move('uploads/librarys',$video_new_name);
        
        $input['video'] = $video_new_name;
        }
        
        $library->update($input);
        
        return redirect()->route('admin.librarys.index');
    }

    public function show(Library $library)
    {
        abort_unless(\Gate::allows('library_show'), 403);

        return view('admin.librarys.show', compact('library'));
    }

    public function destroy(Library $library)
    {
        abort_unless(\Gate::allows('library_delete'), 403);
        
        //delete video
        unlink(public_path() . $library->video);
        //delete library
        $library->delete();

        return back();
    }

    public function massDestroy(MassDestroyLibraryRequest $request)
    {
        $libraries = Library::whereIn('id', request('ids'))->get();
        foreach($libraries as $library){
            //delete video
            unlink(public_path() . $library->video);
            //delete library
            $library->delete();
        }
        
        return response(null, 204);
    }
}


resources/views/admin/librarys/create.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.create') }} {{ trans('global.librarys.title_singular') }}
    </div>

    <div class="card-body">
        <form action="{{ route("admin.librarys.store") }}" method="POST" enctype="multipart/form-data">
            @csrf
            <div class="form-group {{ $errors->has('name') ? 'has-error' : '' }}">
                <label for="name">{{ trans('global.librarys.fields.name') }}*</label>
                <input type="text" id="name" name="name" class="form-control" value="{{ old('name', isset($library) ? $library->name : '') }}">
                @if($errors->has('name'))
                    <em class="invalid-feedback">
                        {{ $errors->first('name') }}
                    </em>
                @endif
                <p class="helper-block">
                    {{ trans('global.librarys.fields.name_helper') }}
                </p>
            </div>
            <div class="form-group {{ $errors->has('video') ? 'has-error' : '' }}">
                <label for="video">{{ trans('global.librarys.fields.video') }}</label>
                <input type="file" id="video" name="video" class="form-control" value="{{ old('video', isset($library) ? $library->video : '') }}">
                @if($errors->has('video'))
                    <em class="invalid-feedback">
                        {{ $errors->first('video') }}
                    </em>
                @endif
                <p class="helper-block">
                    {{ trans('global.librarys.fields.video_helper') }}
                </p>
            </div>
            <div>
                <input class="btn btn-danger" type="submit" value="{{ trans('global.save') }}">
            </div>
        </form>
    </div>
</div>

@endsection

resources/views/admin/librarys/edit.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.edit') }} {{ trans('global.librarys.title_singular') }}
    </div>

    <div class="card-body">
        <form action="{{ route("admin.librarys.update", [$library->id]) }}" method="POST" enctype="multipart/form-data">
            @csrf
            @method('PUT')
            <div class="form-group {{ $errors->has('name') ? 'has-error' : '' }}">
                <label for="name">{{ trans('global.librarys.fields.name') }}*</label>
                <input type="text" id="name" name="name" class="form-control" value="{{ old('name', isset($library) ? $library->name : '') }}">
                @if($errors->has('name'))
                    <em class="invalid-feedback">
                        {{ $errors->first('name') }}
                    </em>
                @endif
                <p class="helper-block">
                    {{ trans('global.librarys.fields.name_helper') }}
                </p>
            </div>
            <div class="form-group {{ $errors->has('video') ? 'has-error' : '' }}">
                <label for="video">{{ trans('global.librarys.fields.video') }}</label>
                <input type="file" id="video" name="video" class="form-control" value="{{ old('video', isset($library) ? $library->video : '') }}" step="0.01">
                @if($errors->has('video'))
                    <em class="invalid-feedback">
                        {{ $errors->first('video') }}
                    </em>
                @endif
                <p class="helper-block">
                    {{ trans('global.librarys.fields.video_helper') }}
                </p>
            </div>
            <div>
                <input class="btn btn-danger" type="submit" value="{{ trans('global.save') }}">
            </div>
        </form>
    </div>
</div>

@endsection

resources/views/admin/librarys/index.blade.php
@extends('layouts.admin')
@section('content')
@can('library_create')
    <div style="margin-bottom: 10px;" class="row">
        <div class="col-lg-12">
            <a class="btn btn-success" href="{{ route("admin.librarys.create") }}">
                {{ trans('global.add') }} {{ trans('global.librarys.title_singular') }}
            </a>
        </div>
    </div>
@endcan
<div class="card">
    <div class="card-header">
        {{ trans('global.librarys.title_singular') }} {{ trans('global.list') }}
    </div>

    <div class="card-body">
        <div class="table-responsive">
            <table class=" table table-bordered table-striped table-hover datatable">
                <thead>
                    <tr>
                        <th width="10">

                        </th>
                        <th>
                            {{ trans('global.librarys.fields.name') }}
                        </th>
                        <th>
                            {{ trans('global.librarys.fields.video') }}
                        </th>
                        <th>
                            &nbsp;
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($librarys as $key => $library)
                        <tr data-entry-id="{{ $library->id }}">
                            <td>

                            </td>
                            <td>
                                {{ $library->name ?? '' }}
                            </td>
                            <td>
                               <video controls width="400" height="150">
                               <source src="{{ asset($library->video) }}" type="video/mp4">
                               </video>
                            </td>
                            <td>
                                @can('library_show')
                                    <a class="btn btn-xs btn-primary" href="{{ route('admin.librarys.show', $library->id) }}">
                                        {{ trans('global.view') }}
                                    </a>
                                @endcan
                                @can('library_edit')
                                    <a class="btn btn-xs btn-info" href="{{ route('admin.librarys.edit', $library->id) }}">
                                        {{ trans('global.edit') }}
                                    </a>
                                @endcan
                                @can('library_delete')
                                    <form action="{{ route('admin.librarys.destroy', $library->id) }}" method="POST" onsubmit="return confirm('{{ trans('global.areYouSure') }}');" style="display: inline-block;">
                                        <input type="hidden" name="_method" value="DELETE">
                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                        <input type="submit" class="btn btn-xs btn-danger" value="{{ trans('global.delete') }}">
                                    </form>
                                @endcan
                            </td>

                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>
@section('scripts')
@parent
<script>
    $(function () {
  let deleteButtonTrans = '{{ trans('global.datatables.delete') }}'
  let deleteButton = {
    text: deleteButtonTrans,
    url: "{{ route('admin.librarys.massDestroy') }}",
    className: 'btn-danger',
    action: function (e, dt, node, config) {
      var ids = $.map(dt.rows({ selected: true }).nodes(), function (entry) {
          return $(entry).data('entry-id')
      });

      if (ids.length === 0) {
        alert('{{ trans('global.datatables.zero_selected') }}')

        return
      }

      if (confirm('{{ trans('global.areYouSure') }}')) {
        $.ajax({
          headers: {'x-csrf-token': _token},
          method: 'POST',
          url: config.url,
          data: { ids: ids, _method: 'DELETE' }})
          .done(function () { location.reload() })
      }
    }
  }
  let dtButtons = $.extend(true, [], $.fn.dataTable.defaults.buttons)
@can('library_delete')
  dtButtons.push(deleteButton)
@endcan

  $('.datatable:not(.ajaxTable)').DataTable({ buttons: dtButtons })
})

</script>
@endsection
@endsection

resources/views/admin/librarys/show.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.show') }} {{ trans('global.librarys.title') }}
    </div>

    <div class="card-body">
        <table class="table table-bordered table-striped">
            <tbody>
                <tr>
                    <th>
                        {{ trans('global.librarys.fields.name') }}
                    </th>
                    <td>
                        {{ $library->name }}
                    </td>
                </tr>
                <tr>
                    <th>
                        {{ trans('global.librarys.fields.video') }}
                    </th>
                    <td>
                        {{ $library->video }}
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
</div>

@endsection