routes/web.php
<?php

//facebook login
Route::get('login/facebook', 'Auth\LoginController@redirectToProvider')->name('login.facebook');
Route::get('login/facebook/callback', 'Auth\LoginController@handleProviderCallback');

Route::group(['middleware' => 'guest'], function () {
    Route::get('register', 'FrontendController@register'); //don't know what is this
    Route::post('register', 'FrontendController@StoreRegister');// don't know what is this

    Route::get('createHere', 'FrontendController@createHere'); // step one for all types

    Route::get('registerfront', 'FrontendController@registerfront'); //for public user register by facebook

    Route::get('trade-register', 'FrontendController@trade_register');          //step 1 for trade visitor register
    Route::get('groupleader-register', 'FrontendController@groupleader_register'); //step 1 for groupleader register
    Route::get('register-exhibitor', 'FrontendController@register_exhibitor');  //step 1 for exhibitor register
    Route::get('register-tourguide', 'FrontendController@register_tourguide');  //step 1 for tourguide register

    Route::post('company-info', 'FrontendController@register2')->name('register2'); // step 2 for all types
    Route::post('individual-profile', 'FrontendController@register3')->name('register3');// step 3 for all types
    Route::post('users_login', 'FrontendController@individual_profile')->name('store.user'); // store step

});

Auth::routes(['register' => false]);


Route::get('/', 'FrontendController@index');
Route::get('exhibitor', 'FrontendController@exhibitor');
Route::get('visitor', 'FrontendController@visitor');
Route::get('library', 'FrontendController@library');
Route::get('privacy', 'FrontendController@privacy');
Route::get('tourguide', 'FrontendController@tourguide');

Route::get('termsandcondition', 'FrontendController@termsandcondition');

//Route::post('company-info', 'FrontendController@company_info');

Route::get('tripfam', 'FrontendController@tripfams');
Route::post('tripfam', 'FrontendController@tripfam');


Route::get('news/{id}', 'FrontendController@news');
Route::get('outer-news', 'FrontendController@outer_news');
Route::get('about', 'FrontendController@About');
Route::get('contact', 'FrontendController@contact');
Route::post('mail', 'FrontendController@contacts')->name('mail');
Route::get('sponsored', 'FrontendController@sponsored');
Route::get('destinationpartner', 'FrontendController@destinationpartner');


Route::redirect('/home', 'admin');


Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth']], function () {

    Route::get('/', 'DashboardController@index')->name('home');

    Route::delete('permissions/destroy', 'PermissionsController@massDestroy')->name('permissions.massDestroy');

    Route::resource('permissions', 'PermissionsController');

    Route::delete('roles/destroy', 'RolesController@massDestroy')->name('roles.massDestroy');

    Route::resource('roles', 'RolesController');

    Route::delete('users/destroy', 'UsersController@massDestroy')->name('users.massDestroy');

    Route::resource('users', 'UsersController');

    Route::delete('products/destroy', 'ProductsController@massDestroy')->name('products.massDestroy');

    Route::resource('products', 'ProductsController');

    Route::delete('visitors/destroy', 'VisitorsController@massDestroy')->name('visitors.massDestroy');
    Route::resource('visitors', 'VisitorsController');

    Route::delete('exhibitors/destroy', 'ExhibitorsController@massDestroy')->name('exhibitors.massDestroy');
    Route::resource('exhibitors', 'ExhibitorsController')->only('index', 'show', 'destroy');

    Route::delete('tourguides/destroy', 'TourGuidesController@massDestroy')->name('tourguides.massDestroy');
    Route::resource('tourguides', 'TourGuidesController')->only('index', 'show', 'destroy');


    Route::delete('searchs/destroy', 'SearchController@massDestroy')->name('searchs.massDestroy');

    Route::resource('searchs', 'SearchController');

    Route::delete('rates/destroy', 'RatesController@massDestroy')->name('rates.massDestroy');

    Route::resource('rates', 'RatesController');

    Route::delete('forms/destroy', 'FormsController@massDestroy')->name('forms.massDestroy');

    Route::resource('forms', 'FormsController');

    Route::delete('offers/destroy', 'OffersController@massDestroy')->name('offers.massDestroy');
    Route::resource('offers', 'OffersController');


    Route::post('results', 'ResultsController@result')->name('results');
    Route::get('results/show/profile/{id}', 'ResultsController@showProfile')->name('results.show.profile');

    Route::delete('abouts/destroy', 'AboutController@massDestroy')->name('abouts.massDestroy');

    Route::resource('abouts', 'AboutController');

    Route::delete('slides/destroy', 'SlideController@massDestroy')->name('slides.massDestroy');

    Route::resource('slides', 'SlideController');

    Route::delete('leaders/destroy', 'LeaderController@massDestroy')->name('leaders.massDestroy');
    Route::resource('leaders', 'LeaderController')->only('index', 'show', 'destroy');

    Route::delete('librarys/destroy', 'LibraryController@massDestroy')->name('librarys.massDestroy');

    Route::resource('librarys', 'LibraryController');

    Route::delete('contactus/destroy', 'ContactUsController@massDestroy')->name('contactus.massDestroy');

    Route::resource('contactus', 'ContactUsController');

    Route::delete('media/destroy', 'MediaController@massDestroy')->name('media.massDestroy');

    Route::resource('media', 'MediaController');

    Route::delete('dashboard/destroy', 'DashboardController@massDestroy')->name('dashboard.massDestroy');

    Route::resource('dashboard', 'DashboardController');

    Route::delete('articles/destroy', 'ArticleController@massDestroy')->name('articles.massDestroy');

    Route::resource('articles', 'ArticleController');

    Route::delete('fans/destroy', 'FamController@massDestroy')->name('fans.massDestroy');

    Route::resource('fans', 'FamController');

    Route::delete('metas/destroy', 'MetaController@massDestroy')->name('metas.massDestroy');
    Route::resource('metas', 'MetaController');

    Route::resource('sliders', 'SlidersController')->only(['index', 'edit', 'update']);

    Route::delete('myoffers/destroy', 'MyOffersController@massDestroy')->name('myoffers.massDestroy');
    Route::resource('myoffers', 'MyOffersController');


    Route::delete('favourites', 'FavouritesController@massDestroy')->name('favourites.massDestroy');
    Route::get('favourites', 'FavouritesController@index')->name('favourites.index');
    Route::get('favourites/{id}', 'FavouritesController@show')->name('favourites.show');
    Route::post('favourites', 'FavouritesController@addFavourite')->name('favourites.add');
    Route::delete('favourites/destroy/{id}', 'FavouritesController@deleteFavourite')->name('favourites.delete');

    Route::get('edit/profile', 'ProfileController@edit')->name('edit.profile');
    Route::patch('edit/profile', 'ProfileController@update')->name('update.profile');
    Route::get('show/profile', 'ProfileController@show')->name('show.profile');
    Route::post('download/{id}', 'ProfileController@Download')->name('companyProfile.download');


});

app/Http/Controllers/Admin/ResultsController.php
<?php

namespace App\Http\Controllers\Admin;


use App\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\DB;

class ResultsController extends Controller
{
    public function result(Request $request)
    {

        abort_unless(\Gate::allows('results_access'), 403);
//        $user = DB::table('users')
//            ->whereJsonContains('travel', ['Adoption'])
//            ->get();
//        dd($user);
//        dd(DB::table('users')
//            ->whereJsonContains('languages', ['Arabic', 'Bengali'])
//            ->get());
        $input = collect($request->all())->filter(function ($value) {
            return null !== $value;
        })->toArray();
        $companies = DB::table('users')
            ->where('status', 4)
            ->where(function ($query) use ($input) {
                if (array_key_exists('country', $input)) {
                    $query->where('country', $input['country']);
                }
            })->where(function ($query) use ($input) {
                if (array_key_exists('name', $input)) {
                    $query->where('name','like', '%'. $input['name'] . '%');
                }
            })->where(function ($query) use ($input) {
                if (array_key_exists('last_name', $input)) {
                    $query->where('last_name', 'like', '%'. $input['last_name'] . '%');
                }
            })->where(function ($query) use ($input, $request) {
                if (array_key_exists('company', $input)) {
                    $query->where('company', 'like', '%' . $input['company'] . '%');
                }
            })->where(function ($query) use ($input, $request) {
                if (array_key_exists('destination', $input)) {
                    $query->whereJsonContains('destination', $input['destination']);
                }
            })->where(function ($query) use ($input, $request) {
                if (array_key_exists('languages', $input)) {
                    $query->whereJsonContains('languages', $input['languages']);
                }
            })->where(function ($query) use ($input, $request) {
                if (array_key_exists('travel', $input)) {
                    $query->whereJsonContains('travel', $input['travel']);
                }
            })->get();

        return view('admin.results.index', compact('companies'));
    }

    public function showProfile($id){

        return view('admin.results.showProfile', [
           'user' => User::findOrFail($id),
        ]);

    }
}

resources/views/admin/results/index.blade.php
<style>

    @media only screen and (max-width: 768px) {

        .card {

            width: 100% !important;

            overflow-x: scroll !important;

        }


    }

</style>

@extends('layouts.admin')

@section('content')



    <div class="card">

        <div class="card-header">

            {{ trans('global.results.title_singular') }} {{ trans('global.list') }}

        </div>

        <div class="container">

            <div class="result">

                <table class="table table-striped ">

                    <thead>

                    <tr>

                        <th></th>

                        <th scope="col">Company</th>

                        <th scope="col">Full Name</th>

                        <th scope="col">Title</th>

                        <th scope="col">Country</th>

                        <th scope="col">View Profile</th>

                        <th scope="col">Make Favourite</th>

                        <th scope="col">Appointment Booking</th>

                        1

                    </tr>

                    </thead>

                    <tbody>


                    @php $i = 1 @endphp

                    @forelse($companies as $company)

                        <tr>

                            <td>{{$i}}</td>

                            <td>{{$company->company}}</td>

                            <td>{{$company->name . ' '. $company->last_name}}</td>

                            <td>{{$company->title}}</td>

                            <td>{{$company->country}}</td>

                            <td><a href="{{route('admin.results.show.profile', $company->id)}}">Profile</a></td>

                            <td>

                                @php $exist = false @endphp

                                @foreach(Auth::user()->favourites as $favourite)

                                    @if($company->id == $favourite->id)

                                        @php $exist = true @endphp

                                        @break

                                    @else

                                        @php $exist = false @endphp

                                    @endif

                                @endforeach

                                @if($exist)

                                    <button type="submit" data-id="{{$company->id}}"

                                            title="remove from favourites list"

                                            class="remove heart btn btn-border">

                                        <i style="color: red" class="fas fa-heart"></i></button>

                                @else

                                    <button type="submit" data-id="{{$company->id}}" title="add to favourite list"

                                            class="add heart btn btn-border">

                                        <i style="color: red" class="far fa-heart"></i></button>

                                @endif

                            </td>


                            {{$i++}}


                            <td>
                                <a href="#" class="btn btn-success">Book an appointment</a>
                            </td>
                        </tr>

                    @empty

                        <th>

                            No Results

                        </th>

                    @endforelse

                    </tbody>

                </table>


            </div>


        </div>

    </div>



@endsection

@section('scripts')



    <script>

        $(function () {


            $.ajaxSetup({

                headers: {

                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')

                }

            });

            $('.heart').click(function () {

                if ($(this).hasClass("add")) {

                    var company_id = $(this).data('id');

                    var btn = $(this);

                    $.ajax({

                        data: {company_id: company_id, _token: '{{csrf_token()}}'},

                        url: "{{ route('admin.favourites.add') }}",

                        type: "POST",

                        success: function (data) {

                            btn.removeClass('add');

                            btn.addClass('remove');

                            btn.attr('title', 'remove from favourites list');

                            btn.children().removeClass('far').addClass('fas');

                        },

                    });

                } else if ($(this).hasClass("remove")) {

                    var company_id = $(this).data('id');

                    var btn = $(this);

                    $.ajax({

                        type: "DELETE",

                        url: "{{ route('admin.favourites.add') }}" + '/destroy/' + company_id,

                        success: function (data) {

                            btn.removeClass('remove');

                            btn.attr('title', 'add to favourites list');

                            btn.addClass('add');

                            btn.children().removeClass('fas').addClass('far');

                        }

                    });

                }


            });

        });


    </script>

@endsection

resources/views/admin/results/showProfile.blade.php
@extends('layouts.admin')
@section('content')

    <div class="card">
        <div class="card-header">
            {{ trans('global.show') }} {{ trans('global.user.title') }}
        </div>

        <div class="card-body">
            <table class="table table-bordered table-striped">
                <tbody>
                <tr>
                    <th>
                        {{ trans('global.user.fields.type') }}
                    </th>
                    <td>
                        {{ $user->type }}
                    </td>
                </tr>
                <tr>
                    <th>
                        {{ trans('global.user.fields.name') }}
                    </th>
                    <td>
                        {{ $user->name }}
                    </td>
                </tr>
                <tr>
                    <th>
                        {{ trans('global.user.fields.last-name') }}
                    </th>
                    <td>
                        {{ $user->last_name }}
                    </td>
                </tr>
                <tr>
                    <th>
                        {{ trans('global.user.fields.imgPersonal') }}
                    </th>
                    <td>
                        <img src="{{ asset($user->imgPersonal) }}" style="height: 50px; width: 100px">
                    </td>
                </tr>
                <tr>
                    <th>
                        {{ trans('global.user.fields.company') }}
                    </th>
                    <td>
                        {{ $user->company }}
                    </td>
                </tr>
                <tr>
                    <th>
                        {{ trans('global.user.fields.imgCompany') }}
                    </th>
                    <td>
                        <img src="{{asset( $user->imgCompany) }}" style="height: 50px; width: 100px">
                    </td>
                </tr>
                <tr>
                    <th>
                        {{ trans('global.user.fields.website') }}
                    </th>
                    <td>
                        <a href="{{ $user->website }}" target="_blank">{{$user->website}}</a>
                    </td>
                </tr>
                @if($user->facebook != null)
                    <tr>
                        <th>
                            {{ trans('global.user.fields.facebook') }}
                        </th>
                        <td>
                            <a href="{{ $user->facebook }}" target="_blank">Facebook</a>
                        </td>
                    </tr>
                @endif
                @if($user->linkedin != null)
                    <tr>
                        <th>
                            {{ trans('global.user.fields.linkedin') }}
                        </th>
                        <td>
                            <a href="{{ $user->linkedin }}" target="_blank">LinkedIn</a>
                        </td>
                    </tr>
                @endif
                @if($user->twitter != null)
                    <tr>
                        <th>
                            {{ trans('global.user.fields.twitter') }}
                        </th>
                        <td>
                            <a href="{{ $user->twitter }}" target="_blank">Twitter</a>
                        </td>
                    </tr>
                @endif
                @if($user->instgram != null)
                    <tr>
                        <th>
                            {{ trans('global.user.fields.instgram') }}
                        </th>
                        <td>
                            <a href="{{ $user->instgram }}" target="_blank">Instagram</a>
                        </td>
                    </tr>
                @endif
                <tr>
                    <th>
                        {{ trans('global.user.fields.designation') }}
                    </th>
                    <td>
                        {{ $user->designation }}
                    </td>
                </tr>
                <tr>
                    <th>
                        {{ trans('global.user.fields.zip-code') }}
                    </th>
                    <td>
                        {{ $user->zip_code }}
                    </td>
                </tr>
                <tr>
                    <th>
                        {{ trans('global.user.fields.country') }}
                    </th>
                    <td>
                        {{ $user->country }}
                    </td>
                </tr>
                @if($user->travel != null)
                    <tr>
                        <th>
                            {{ trans('global.user.fields.travel') }}
                        </th>

                        <td>
                            <ul>

                                @foreach($user->travel as $travel)
                                    <li>{{$travel}}</li>
                                @endforeach

                            </ul>
                        </td>
                    </tr>
                @endif
                @if($user->languages != null)
                    <tr>
                        <th>
                            {{ trans('global.user.fields.languages') }}
                        </th>
                        <td>
                            <ul>
                                @foreach($user->languages as $language)
                                    <li>{{$language}}</li>
                                @endforeach
                            </ul>
                        </td>
                    </tr>
                @endif
                @if($user->destination != null)
                    <tr>
                        <th>
                            {{ trans('global.user.fields.destination') }}
                        </th>
                        <td>
                            <ul>
                                @foreach($user->destination as $destination)
                                    <li>{{$destination}}</li>
                                @endforeach
                            </ul>
                        </td>
                    </tr>
                @endif
                @if($user->payment_status == 1)
                    <tr>
                        <th>
                            {{ trans('global.user.fields.company_profile') }}
                        </th>
                        <td>
                            @if(!empty($user->company_profile))
                                <form id="download" action="{{route('admin.companyProfile.download', $user->id)}}"
                                      method="POST"
                                      style="display: inline-block;">
                                    @csrf
                                    <a href="#"
                                       onclick="event.preventDefault(); document.getElementById('download').submit();">Download
                                        Company Profile</a>
                                </form>
                            @endif
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('global.user.fields.brochure') }}
                        </th>
                        <td>
                            <img src="{{asset( $user->brochure) }}" style="height: 50px; width: 100px">
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('global.user.fields.youtubeLink') }}
                        </th>
                        <td class="text-sm-center">
                            @php $videoId = getYoutubeEmbedUrl($user->youtubeLink) @endphp

                            @if($videoId)
                                <iframe width="50%" height="300"
                                        src="https://www.youtube-nocookie.com/embed/{{$videoId}}"
                                        allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture"
                                        allowfullscreen></iframe>
                            @endif
                        </td>
                    </tr>
                @endif
                </tbody>
            </table>
        </div>
    </div>

@endsection