routes/web.php
<?php

//facebook login
Route::get('login/facebook', 'Auth\LoginController@redirectToProvider')->name('login.facebook');
Route::get('login/facebook/callback', 'Auth\LoginController@handleProviderCallback');

Route::group(['middleware' => 'guest'], function () {
    Route::get('register', 'FrontendController@register'); //don't know what is this
    Route::post('register', 'FrontendController@StoreRegister');// don't know what is this

    Route::get('createHere', 'FrontendController@createHere'); // step one for all types

    Route::get('registerfront', 'FrontendController@registerfront'); //for public user register by facebook

    Route::get('trade-register', 'FrontendController@trade_register');          //step 1 for trade visitor register
    Route::get('groupleader-register', 'FrontendController@groupleader_register'); //step 1 for groupleader register
    Route::get('register-exhibitor', 'FrontendController@register_exhibitor');  //step 1 for exhibitor register
    Route::get('register-tourguide', 'FrontendController@register_tourguide');  //step 1 for tourguide register

    Route::post('company-info', 'FrontendController@register2')->name('register2'); // step 2 for all types
    Route::post('individual-profile', 'FrontendController@register3')->name('register3');// step 3 for all types
    Route::post('users_login', 'FrontendController@individual_profile')->name('store.user'); // store step

});

Auth::routes(['register' => false]);


Route::get('/', 'FrontendController@index');
Route::get('exhibitor', 'FrontendController@exhibitor');
Route::get('visitor', 'FrontendController@visitor');
Route::get('library', 'FrontendController@library');
Route::get('privacy', 'FrontendController@privacy');
Route::get('tourguide', 'FrontendController@tourguide');

Route::get('termsandcondition', 'FrontendController@termsandcondition');

//Route::post('company-info', 'FrontendController@company_info');

Route::get('tripfam', 'FrontendController@tripfams');
Route::post('tripfam', 'FrontendController@tripfam');


Route::get('news/{id}', 'FrontendController@news');
Route::get('outer-news', 'FrontendController@outer_news');
Route::get('about', 'FrontendController@About');
Route::get('contact', 'FrontendController@contact');
Route::post('mail', 'FrontendController@contacts')->name('mail');
Route::get('sponsored', 'FrontendController@sponsored');
Route::get('destinationpartner', 'FrontendController@destinationpartner');


Route::redirect('/home', 'admin');


Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth']], function () {

    Route::get('/', 'DashboardController@index')->name('home');

    Route::delete('permissions/destroy', 'PermissionsController@massDestroy')->name('permissions.massDestroy');

    Route::resource('permissions', 'PermissionsController');

    Route::delete('roles/destroy', 'RolesController@massDestroy')->name('roles.massDestroy');

    Route::resource('roles', 'RolesController');

    Route::delete('users/destroy', 'UsersController@massDestroy')->name('users.massDestroy');

    Route::resource('users', 'UsersController');

    Route::delete('products/destroy', 'ProductsController@massDestroy')->name('products.massDestroy');

    Route::resource('products', 'ProductsController');

    Route::delete('visitors/destroy', 'VisitorsController@massDestroy')->name('visitors.massDestroy');
    Route::resource('visitors', 'VisitorsController');

    Route::delete('exhibitors/destroy', 'ExhibitorsController@massDestroy')->name('exhibitors.massDestroy');
    Route::resource('exhibitors', 'ExhibitorsController')->only('index', 'show', 'destroy');

    Route::delete('tourguides/destroy', 'TourGuidesController@massDestroy')->name('tourguides.massDestroy');
    Route::resource('tourguides', 'TourGuidesController')->only('index', 'show', 'destroy');


    Route::delete('searchs/destroy', 'SearchController@massDestroy')->name('searchs.massDestroy');

    Route::resource('searchs', 'SearchController');

    Route::delete('rates/destroy', 'RatesController@massDestroy')->name('rates.massDestroy');

    Route::resource('rates', 'RatesController');

    Route::delete('forms/destroy', 'FormsController@massDestroy')->name('forms.massDestroy');

    Route::resource('forms', 'FormsController');

    Route::delete('offers/destroy', 'OffersController@massDestroy')->name('offers.massDestroy');
    Route::resource('offers', 'OffersController');


    Route::post('results', 'ResultsController@result')->name('results');
    Route::get('results/show/profile/{id}', 'ResultsController@showProfile')->name('results.show.profile');

    Route::delete('abouts/destroy', 'AboutController@massDestroy')->name('abouts.massDestroy');

    Route::resource('abouts', 'AboutController');

    Route::delete('slides/destroy', 'SlideController@massDestroy')->name('slides.massDestroy');

    Route::resource('slides', 'SlideController');

    Route::delete('leaders/destroy', 'LeaderController@massDestroy')->name('leaders.massDestroy');
    Route::resource('leaders', 'LeaderController')->only('index', 'show', 'destroy');

    Route::delete('librarys/destroy', 'LibraryController@massDestroy')->name('librarys.massDestroy');

    Route::resource('librarys', 'LibraryController');

    Route::delete('contactus/destroy', 'ContactUsController@massDestroy')->name('contactus.massDestroy');

    Route::resource('contactus', 'ContactUsController');

    Route::delete('media/destroy', 'MediaController@massDestroy')->name('media.massDestroy');

    Route::resource('media', 'MediaController');

    Route::delete('dashboard/destroy', 'DashboardController@massDestroy')->name('dashboard.massDestroy');

    Route::resource('dashboard', 'DashboardController');

    Route::delete('articles/destroy', 'ArticleController@massDestroy')->name('articles.massDestroy');

    Route::resource('articles', 'ArticleController');

    Route::delete('fans/destroy', 'FamController@massDestroy')->name('fans.massDestroy');

    Route::resource('fans', 'FamController');

    Route::delete('metas/destroy', 'MetaController@massDestroy')->name('metas.massDestroy');
    Route::resource('metas', 'MetaController');

    Route::resource('sliders', 'SlidersController')->only(['index', 'edit', 'update']);

    Route::delete('myoffers/destroy', 'MyOffersController@massDestroy')->name('myoffers.massDestroy');
    Route::resource('myoffers', 'MyOffersController');


    Route::delete('favourites', 'FavouritesController@massDestroy')->name('favourites.massDestroy');
    Route::get('favourites', 'FavouritesController@index')->name('favourites.index');
    Route::get('favourites/{id}', 'FavouritesController@show')->name('favourites.show');
    Route::post('favourites', 'FavouritesController@addFavourite')->name('favourites.add');
    Route::delete('favourites/destroy/{id}', 'FavouritesController@deleteFavourite')->name('favourites.delete');

    Route::get('edit/profile', 'ProfileController@edit')->name('edit.profile');
    Route::patch('edit/profile', 'ProfileController@update')->name('update.profile');
    Route::get('show/profile', 'ProfileController@show')->name('show.profile');
    Route::post('download/{id}', 'ProfileController@Download')->name('companyProfile.download');


});

app/Article.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
 
class Article extends Model
{
    
     use SoftDeletes;
     
    
      protected $dates = [
        'created_at',
        'updated_at',
        'deleted_at'
    ];
    
     protected $fillable = [
        'title',
        'description',
        'images',
        'created_at',
        'updated_at',
        'deleted_at'
    ];
    
    // protected $castas = [
    //     'images' => 'array'
    // ];
}

app/Http/Controllers/Admin/ArticleController.php
<?php

namespace App\Http\Controllers\Admin;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Http\Requests\MassDestroyArticleRequest;
use App\Http\Requests\StoreArticleRequest;
use App\Http\Requests\UpdateArticleRequest;
use App\Article;

class ArticleController extends Controller
{
    public function index()
    {
        abort_unless(\Gate::allows('article_access'), 403);

        $articles = Article::all();

        return view('admin.articles.index', compact('articles'));
    }

    public function create()
    {
        abort_unless(\Gate::allows('article_create'), 403);

        return view('admin.articles.create');
    }

    public function store(Request $request)
    {
        abort_unless(\Gate::allows('article_create'), 403);

        $images = $request->file('image');
        $image_new_name = time().$images->getClientOriginalName();
        $images->move(public_path() . '/uploads/articles/',$image_new_name);
        
        $article = Article::create([
               'title'=>$request->title,
               'description'=>$request->description,
               'images'=>$image_new_name,
            
            ]);
            
        return redirect()->route('admin.articles.index');
    }

    public function edit(Article $article)
    {
        abort_unless(\Gate::allows('article_edit'), 403);

        return view('admin.articles.edit', compact('article'));
    }

    public function update(Request $request, Article $article)
    {
        abort_unless(\Gate::allows('article_edit'), 403);

        if($request->hasFile('images')){
        $images = $request->file('images');
        $image_new_name = time().$images->getClientOriginalName();
        $images->move(public_path() . '/uploads/articles/',$image_new_name);
        $article->images = $image_new_name;
        }
        
        $article->update([
            $article->title=$request->title,
            $article->description=$request->description,
            
        ]);
        
        $article->save();
        return redirect()->route('admin.articles.index');
    }

    public function show(Article $article)
    {
        abort_unless(\Gate::allows('article_show'), 403);

        return view('admin.articles.show', compact('article'));
    }

    public function destroy(Article $article)
    {
        abort_unless(\Gate::allows('article_delete'), 403);

        $article->delete();

        return back();
    }

    public function massDestroy(MassDestroyArticleRequest $request)
    {
        Article::whereIn('id', request('ids'))->delete();

        return response(null, 204);
    }
}



resources/views/admin/articles/create.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.create') }} {{ trans('global.news.title_singular') }}
    </div>

    <div class="card-body">
        <form action="{{ route("admin.articles.store") }}" method="POST" enctype="multipart/form-data">
            @csrf
            <div class="form-group {{ $errors->has('title') ? 'has-error' : '' }}">
                <label for="title">{{ trans('global.news.fields.title') }}*</label>
                <input type="text" id="title" name="title" class="form-control" value="{{ old('title', isset($article) ? $article->title : '') }}">
                @if($errors->has('title'))
                    <em class="invalid-feedback">
                        {{ $errors->first('title') }}
                    </em>
                @endif
                <p class="helper-block">
                    {{ trans('global.news.fields.title_helper') }}
                </p>
            </div>
            <div class="form-group {{ $errors->has('description') ? 'has-error' : '' }}">
                <label for="description">{{ trans('global.news.fields.description') }}</label>
                <textarea id="description" name="description" class="form-control ">{{ old('description', isset($article) ? $article->description : '') }}</textarea>
                @if($errors->has('description'))
                    <em class="invalid-feedback">
                        {{ $errors->first('description') }}
                    </em>
                @endif
                <p class="helper-block">
                    {{ trans('global.news.fields.description_helper') }}
                </p>
            </div>
            <div class="form-group {{ $errors->has('image') ? 'has-error' : '' }}">
                <label for="image">{{ trans('global.news.fields.images') }}</label>
                <input type="file" id="image" name="image" class="form-control" value="{{ old('images', isset($article) ? $article->images : '') }}">
                @if($errors->has('image'))
                    <em class="invalid-feedback">
                        {{ $errors->first('image') }}
                    </em>
                @endif
                <p class="helper-block">
                    {{ trans('global.news.fields.images_helper') }}
                </p>
            </div>
            <div>
                <input class="btn btn-danger" type="submit" value="{{ trans('global.save') }}">
            </div>
        </form>
    </div>
</div>

@endsection

resources/views/admin/articles/edit.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.edit') }} {{ trans('global.news.title_singular') }}
    </div>

    <div class="card-body">
        <form action="{{ route("admin.articles.update", [$article->id]) }}" method="POST" enctype="multipart/form-data">
            @csrf
            @method('PUT')
            <div class="form-group {{ $errors->has('title') ? 'has-error' : '' }}">
                <label for="title">{{ trans('global.news.fields.title') }}*</label>
                <input type="text" id="title" name="title" class="form-control" value="{{ old('title', isset($article) ? $article->title : '') }}">
                @if($errors->has('title'))
                    <em class="invalid-feedback">
                        {{ $errors->first('title') }}
                    </em>
                @endif
                <p class="helper-block">
                    {{ trans('global.news.fields.title_helper') }}
                </p>
            </div>
            <div class="form-group {{ $errors->has('description') ? 'has-error' : '' }}">
                <label for="description">{{ trans('global.news.fields.description') }}</label>
                <textarea id="description" name="description" class="form-control ">{{ old('description', isset($article) ? $article->description : '') }}</textarea>
                @if($errors->has('description'))
                    <em class="invalid-feedback">
                        {{ $errors->first('description') }}
                    </em>
                @endif
                <p class="helper-block">
                    {{ trans('global.news.fields.description_helper') }}
                </p>
            </div>
            <div class="form-group {{ $errors->has('images') ? 'has-error' : '' }}">
                <label for="images">{{ trans('global.news.fields.images') }}</label>
                <input type="file" id="images" name="images" class="form-control" value="{{ old('images', isset($article) ? $article->images : '') }}">
                @if($errors->has('images'))
                    <em class="invalid-feedback">
                        {{ $errors->first('images') }}
                    </em>
                @endif
                <p class="helper-block">
                    {{ trans('global.news.fields.images_helper') }}
                </p>
            </div>
            <div>
                <input class="btn btn-danger" type="submit" value="{{ trans('global.save') }}">
            </div>
        </form>
    </div>
</div>

@endsection

resources/views/admin/articles/index.blade.php
@extends('layouts.admin')
@section('content')
@can('article_create')
    <div style="margin-bottom: 10px;" class="row">
        <div class="col-lg-12">
            <a class="btn btn-success" href="{{ route("admin.articles.create") }}">
                {{ trans('global.add') }} {{ trans('global.news.title_singular') }}
            </a>
        </div>
    </div>
@endcan
<div class="card">
    <div class="card-header">
        {{ trans('global.news.title_singular') }} {{ trans('global.list') }}
    </div>

    <div class="card-body">
        <div class="table-responsive">
            <table class=" table table-bordered table-striped table-hover datatable">
                <thead>
                    <tr>
                        <th width="10">

                        </th>
                        <th>
                            {{ trans('global.news.fields.title') }}
                        </th>
                        <th>
                            {{ trans('global.news.fields.description') }}
                        </th>
                        <th>
                            {{ trans('global.news.fields.images') }}
                        </th>
                        <th>
                            {{ trans('global.news.fields.created_at') }}
                        </th>
                        <th>
                            &nbsp;
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($articles as $key => $article)
                        <tr data-entry-id="{{ $article->id }}">
                            <td>

                            </td>
                            <td>
                                {{ $article->title ?? '' }}
                            </td>
                            <td>
                                {{ substr(strip_tags($article->description) ,0,60) ?? ''}}
                                @can('article_show')
                                    <a class="btn btn-xs btn-info" href="{{ route('admin.articles.show', $article->id) }}">
                                        Read more..
                                    </a>
                                @endcan
                            </td>
                            <td>
                                <img src="{{ asset ('uploads/articles/'. $article->images) }}" width="100" alt=" {{ trans('global.news.title_singular') }}">
                            </td>
                            <td>
                                {{ $article->created_at ?? '' }}
                            </td>
                            <td>
                                @can('article_show')
                                    <a class="btn btn-xs btn-primary" href="{{ route('admin.articles.show', $article->id) }}">
                                        {{ trans('global.view') }}
                                    </a>
                                @endcan
                                @can('article_edit')
                                    <a class="btn btn-xs btn-info" href="{{ route('admin.articles.edit', $article->id) }}">
                                        {{ trans('global.edit') }}
                                    </a>
                                @endcan
                                @can('article_delete')
                                    <form action="{{ route('admin.articles.destroy', $article->id) }}" method="POST" onsubmit="return confirm('{{ trans('global.areYouSure') }}');" style="display: inline-block;">
                                        <input type="hidden" name="_method" value="DELETE">
                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                        <input type="submit" class="btn btn-xs btn-danger" value="{{ trans('global.delete') }}">
                                    </form>
                                @endcan
                            </td>

                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>
@section('scripts')
@parent
<script>
    $(function () {
  let deleteButtonTrans = '{{ trans('global.datatables.delete') }}'
  let deleteButton = {
    text: deleteButtonTrans,
    url: "{{ route('admin.articles.massDestroy') }}",
    className: 'btn-danger',
    action: function (e, dt, node, config) {
      var ids = $.map(dt.rows({ selected: true }).nodes(), function (entry) {
          return $(entry).data('entry-id')
      });

      if (ids.length === 0) {
        alert('{{ trans('global.datatables.zero_selected') }}')

        return
      }

      if (confirm('{{ trans('global.areYouSure') }}')) {
        $.ajax({
          headers: {'x-csrf-token': _token},
          method: 'POST',
          url: config.url,
          data: { ids: ids, _method: 'DELETE' }})
          .done(function () { location.reload() })
      }
    }
  }
  let dtButtons = $.extend(true, [], $.fn.dataTable.defaults.buttons)
@can('article_delete')
  dtButtons.push(deleteButton)
@endcan

  $('.datatable:not(.ajaxTable)').DataTable({ buttons: dtButtons })
})

</script>
@endsection
@endsection

resources/views/admin/articles/show.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.show') }} {{ trans('global.news.title') }}
    </div>

    <div class="card-body">
        <table class="table table-bordered table-striped">
            <tbody>
                <tr>
                    <th>
                        {{ trans('global.news.fields.title') }}
                    </th>
                    <td>
                        {{ $article->title }}
                    </td>
                </tr>
                <tr>
                    <th>
                        {{ trans('global.news.fields.description') }}
                    </th>
                    <td>
                        {!! $article->description !!}
                    </td>
                </tr>
                <tr>
                    <th>
                        {{ trans('global.news.fields.images') }}
                    </th>
                    <td>
                         <img src="{{ asset ('uploads/articles/'. $article->images) }}" width="100" alt=" {{ trans('global.news.title_singular') }}">
                    </td>
                </tr>
                <tr>
                    <th>
                        {{ trans('global.news.fields.created_at') }}
                    </th>
                    <td>
                         {{ $article->created_at ?? '' }}
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
</div>

@endsection